import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Providers } from "@/components/providers";
import { BottomTabBar } from "@/components/nav/bottom-tab-bar";
import { createClient } from "@/lib/supabase/server";
import { listAccounts } from "@/lib/db/accounts";
import { listCategories } from "@/lib/db/categories";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// viewport-fit=cover is required for env(safe-area-inset-bottom) in the
// bottom tab bar to resolve to anything other than 0 - without it, iOS
// treats the viewport as if there's no notch/home-indicator to avoid.
export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
};

export default async function RootLayout({ children }: LayoutProps<"/">) {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  const [accounts, categories] = user
    ? await Promise.all([
        listAccounts(supabase, user.id),
        listCategories(supabase, user.id),
      ])
    : [[], []];

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Providers>
          {/* 4rem matches BottomTabBar's own min-h-16, so content clears
              the fixed bar exactly rather than by a guessed margin. */}
          <div className="flex-1 pb-[calc(4rem+env(safe-area-inset-bottom))]">
            {children}
          </div>
          <BottomTabBar accounts={accounts} categories={categories} />
        </Providers>
      </body>
    </html>
  );
}
